name: build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: iNoi-Web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Checkout dist repo
        uses: actions/checkout@v4
        with:
          repository: li-peifeng/iNoi-Dist
          ref: dev
          path: iNoi-Dist
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        run: |
          cd iNoi-Web
          pnpm install --no-frozen-lockfile
          pnpm build
          cd ..

      - name: Commit dist
        run: |
          cd iNoi-Dist
          rm -rf dist
          cp -r ../iNoi-Web/dist .
          git add .
          git config --local user.email "inoi@peifeng.li"
          git config --local user.name "LEO"
          git commit --amend -m "upload dev dist"
          cd ..

      - name: Upload dist files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: dev
          directory: iNoi-Dist
          repository: li-peifeng/iNoi-Dist
          force: true
